### ISSUE TITLE
e-PRIA's ei saa mesilat kustutada

### ISSUE THREAD

**Issue by tormi** [honeymarket/mesilad.mesindus.ee#39]
Ardi Asten kurtis Pärnu teabepäevadel (https://github.com/honeymarket/mesi.ee/issues/28), et e-PRIAs ei saa mesilat kustutada. Saab ainult perede arvu nullida.

**Comment by erkinaumanis** [comment]
Mesila kustutamine on täitsa tehtav. Regasin oma mesilad just firma alla ja ennem samasse kohta regada ei saanud, kui eraisiku alt oli kustutatud samas kohas... 
Eks ta tüütu on, aga täiesti tehtav.

**Comment by erkinaumanis** [comment]
võin pärast vaadata, mis sammud täpsemalt pidi läbi käima

**Comment by tormi** [comment]
> võin pärast vaadata, mis sammud täpsemalt pidi läbi käima
:+1:

**Comment by tormi** [comment]
> Regasin oma mesilad just firma alla

Mul on ka just see teema üleval: https://github.com/honeymarket/mesi.ee/issues/10#issuecomment-291111500

**Comment by tormi** [comment]
@erkinaumanis, leidsid mahti?

**Comment by erkinaumanis** [comment]
Nii ... leidsin mahti ja tegin täna mitu kurda isegi .. 
selle peale läheb vaid 2 minutit.
1. Logi sises vanasse e-priasse
2. vali esindatav, kelle alt mesilad kustutada
Et ehitist kustutada, peab see tühi olema. Mul ühes ehitises olid mesilased veel jäänud sisse ja ei lase kustutada.

3. teenused > Andmete Esitamine > Mesilasperede arvu teatamine
4. avane val vormil kustutatavale ehitisele/alale mesilaste arv 0, teistele ehitistele õige number ja esita.
5. teenused > andmete esitamine > ehitise andmete vaatamine
6. all paremal muuda > likvideeri lahtrisse kuupäev valida ja põhjuseks vastav põhjus (tavaliselt muu vms)
7. esita...

Ehitis kustutatakse koheselt.

**Comment by tormi** [comment]
:+1: ! See tuleks nüüd juhendisse lisada, siis saame sulgeda.

**Comment by tormi** [comment]
![screenshot from 2017-05-11 02-00-37](https://cloud.githubusercontent.com/assets/146800/25939683/5f164210-363c-11e7-93fe-1d72fb641376.png)

**Comment by tormi** [comment]
Lisasin [mesindus.ee juhendisse](https://mesindus.ee/pria-juhend) mesila kustutamise juhised: 
![screenshot from 2017-05-11 11-47-29](https://cloud.githubusercontent.com/assets/146800/25940709/af135f16-363f-11e7-813c-1fdd2a9d13b5.png)
